apiVersion: v1
kind: Pod
metadata:
  name: aplicacao
spec:
  containers:
    - name: container-aplicacao-loja
      image: rafanercessian/aplicacao-loja:v1
      ports:
<<<<<<< HEAD
       - containerPort: 80
=======
       - containerPort: 80
>>>>>>> 07e4129eba6c621c12915b65ad3e764fd7da25f2
